#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building opencat-business-service docker ###"
        docker build target/docker -t docker-io.dbc.dk/opencat-business-service:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-io.dbc.dk/opencat-business-service:devel docker-io.dbc.dk/opencat-business-service:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building opencat-business project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac