#!/usr/bin/env bash

mvn clean
rm -rf deploy/* || true
git pull --ff-only || true
docker rm -f docker-metascrum.artifacts.dbccloud.dk/opencat-business-service:devel &>/dev/null || true
docker rmi docker-metascrum.artifacts.dbccloud.dk/opencat-business-service:devel || true
echo "Finished cleaning"
