#!/usr/bin/env bash
docker run --rm -e HOST_USER_ID=$(id -u) \
    -e HOST_USER_GID=$(id -g) \
    --user=$(id -u) \
    -v $(pwd):/home/jsshell \
    --entrypoint "/bin/bash" \
    docker-io.dbc.dk/dbc-jsshell:latest \
    -c '/home/jsshell/template-transpiler/bin/transpile-templates.sh'